language: node_js
node_js: stable
sudo: false
cache:
  directories:
  - node_modules
notifications:
  email:
    recipients:
    - snippet@91h5.cc
    on_success: never
    on_failure: always
install:
- npm install
before_script:
- export TZ='Asia/Shanghai'
- npm install -g gulp
- chmod +x _travis.sh
- npm install -g hexo-cli
script:
- hexo clean && hexo g
- gulp
after_success: 
after_script:
- ./_travis.sh
branches:
  only:
  - master
env:
  global:
  - GH_REF: github.com/zhengxkq/zhengxkq.github.com
  - secure: bOZKm11EtPSpwRcDKNwXB19mU5W/XxW5oAnevh5/2A8TYASoKexI5w3UZiKdrOd+fc9+3gC6EgruX1M0uHu2Z1a3sPgpEAcKOBiC9JlPHqUd2G7QEmi2N73r6OC1ibXtogn7fAigB6Wy9JFcsw960cPhiAdjtz9M8yVS49cc9vo+URJEtR2dLhnBVqmZU4EVSUOZPQIuG8TYJdi5yLvrnJeJWe45tbhfIF79KF7bOcfh/s3HAMdrDbzG5bawPEO2CNBZl4kSmFD0M6kS9o5wlQG52c4cetxJpuTCGvkbmXYJMvyMNTAWhso1s14Qfacpwex+IQgn92bPyXmQLy41vtNzW3K7g994DQpdJ9nR0NmdB8DfNtirriru8hyu5skeJwcsQJkOX9y+bYm89CsBP554XRS5RD5hN8znM1Nmx0+M8Sd+hFn7w+jZkEesLMBxIVlqKVqiUlCGb7jPplItQlqGRr5pflkgS0ZIbElsHbxIFTNat9X/qnIMSS5qg2K1T0wki+txpbdtQcM7ukYeMriZHaPxde9HBA7oPloiZHHPBu+dgOy9KzQi/ER6pCa5BOzjDiv+OBXtlHAJXBHjtKlJZNEOfyYMnmN5Bdj+30XsrrAlOSj8Q5WRQHpt7CiXnPaVZpd7wiCLYs3d3py6cgHtOLLY7crNAgFEudN3qY0=
