language: node_js #使用Node语言环境
node_js: stable #安装稳定版Node

sudo: false  

#cache 启用缓存，加快构建速度
cache: 
  directories:
    - "node_modules"

notifications: #启用通知
  email:
    recipients:
      - zhwxkq@163.com #接收构建消息的邮件 不需要可设置为false
    on_success: never #部署成功时，可设置alway never change
    on_failure: always #部署失败时，同上

# S: Build Lifecycle
install:
  - npm install  #安装依赖

before_script:
  - export TZ='Asia/Shanghai' #设置时区
  - npm install -g gulp  #安装Gulp
  - chmod +x _travis.sh  #授权脚本执行权限

script:
  - mkdir pulbic
  - hexo clean && hexo g #清除缓存并生成静态文件
  # - gulp #执行gulp任务 
after_success: #实行成功时(以后扩展功能使用)

after_script:
  - ./_travis.sh #执行部署脚本
# E: Build LifeCycle

branches:
  only:
    - master #需要监听部署的分支
env:
 global:
    - GH_REF: github.com/zhengxkq/zhengxkq.github.com #更改为自己git地址
    - secure: XXGzEdn6iCnYJfUABIWsJno6dHSJlRRKKhjkV186j4Ie6uHHLCMo35OsnL/YALmtrwFersj9kLgA8HaVNgOitW3JUzgx1EW6bC54VgiHqMyPKWuJzSn59VIq+xutxg2xDDiLIJ3uoDHY9TYxr4C5aE2oSABfUaEqTu7ALcDk8Xy/ODdTkfZSIUGcf+KkPTevjU42Bt+K16ReIehfjSaK9ZXqkaiKKDPFvNCObA7jiO87VuSaxKBx0W5VG4hLCFzBi8Ww0dMbkIrLtZ2U6bEpP2MDc7n7OzMwjRm7tGeBw0ZUtDieexIq/Jcp60vxyuQ9UGayW7AZTULadOoK18XZgZPnQdHc99FFHiOc6/pqrZsTXUuHJX//8US53mn+qJLAqB2kb39sW5NSBH6sCd1U/3QnnJAJTl8ma0z8hiCSUPm5Qsbh0poCtgqdxKGFketthzUwMxyl81Kq+nMM4LJQYpFOP4PrAGz2OmAwtrDK89XpN7vaH7bxf2kn4gEQSXUP17te6vNL1XPqmE0R3B3t9oGRTrw22TlV9YLOBaO5GQAeTn42QjcJQnSLTctMeeB0XRPwJHeL5ZpjQpmvTAr905DGcFXhM7wjsKr3NtOeF1RxwVJCGSroTI+wQnXccVCEXDb/GOw73dHozYByN00beDALlMBSgdKDGzhauWRve3c=
